import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import StudiesModal from '../components/studiesModal'
import LaboralExpModal from '../components/laboralExpModal'
import PersonalProjectsModal from '../components/personalProjectsModal'
import AboutMeModal from '../components/aboutMeModal'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='MainBg text-white'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-white  min-h-screen'>
        <div className='flex w-[60%] absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%]'>
          <img src='/Images/profile.jpg' className='w-[25rem] ProfileImage rounded-full border border-red-500 border-4 border-gray-500'></img>
          <div className='float-left ml-7 flex flex-col justify-between py-7'>
            <h1 className='text-[6rem] leading-[5rem] mb-6'>Kevin Steven Sequeira Garita</h1>
            <div>
              <p className='text-[2rem]'>Ingeniero del Software</p>
              <p>Soy un desarrollador con grandes capacidades de desarrollo de software, con la misma facilidad de trabajar en equipo como de trabajar de manera solitaria, además me encanta aprender nuevas tecnologías y esto implica que si debo investigar como hacer alguna tarea, lo haré de una manera profesional.</p>
            </div>
          </div>
        </div>
      </div>
      <div className='px-[10rem] pb-[10rem]'>
        <div className='flex my-32'>
          <StudiesModal />
        </div>
        <div className='flex my-32 justify-end'>
          <LaboralExpModal />
        </div>
        <div className='flex my-32'>
          <PersonalProjectsModal />
        </div>
        <div className='flex my-32 justify-end'>
          <AboutMeModal />
        </div>
      </div>
    </div>
  )
}
